name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Step 4: Install security validation tools (Bandit, Lynis, Pip-Audit, Safety)
    - name: Install security validation tools
      run: |
        pip install bandit
        pip install pip-audit
        pip install safety
        sudo apt-get update && sudo apt-get install -y lynis

    # Step 5: Set up AWS credentials
    - name: Set up AWS credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region us-east-1

    # Step 6: Prepare test environment
    - name: Prepare test environment
      run: |
        mkdir -p /tmp/testdir
        echo "test content" > /tmp/testdir/testfile.txt
        mkdir -p /tmp/quickbackup
        echo "backup_paths: ['/tmp/testdir']" > /tmp/quickbackup/config.yml
        echo "s3_bucket: 'hybytes-rpm-repo'" >> /tmp/quickbackup/config.yml
      env:
        CONFIG_PATH: /tmp/quickbackup/config.yml

    # Step 7: Run Unit Tests
    - name: Run unit tests
      run: pytest tests/test_unit.py --tb=short
      env:
        CONFIG_PATH: /tmp/quickbackup/config.yml
        PYTHONPATH: ./src

    # Step 8: Run Integration Tests
    - name: Run integration tests
      run: pytest tests/test_integration.py --tb=short
      env:
        CONFIG_PATH: /tmp/quickbackup/config.yml
        PYTHONPATH: ./src

    # Step 9: Run Performance Tests
    - name: Run performance tests
      run: pytest tests/test_performance.py --tb=short
      env:
        CONFIG_PATH: /tmp/quickbackup/config.yml
        PYTHONPATH: ./src

    # Step 10: Run Security Validation Tests (Bandit, Lynis, etc.)
    - name: Run security validation tests
      run: |
        bandit -r src/backup.py -v
        lynis audit system 
        pip-audit 
        safety check 
      env:
        CONFIG_PATH: /tmp/quickbackup/config.yml
        PYTHONPATH: ./src
