name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Step 4: Prepare test environment
    - name: Prepare test environment
      run: |
        mkdir -p /tmp/testdir
        echo "test content" > /tmp/testdir/testfile.txt
        mkdir -p /tmp/quickbackup
        echo "backup_paths: ['/tmp/testdir']" > /tmp/quickbackup/config.yml
        echo "s3_bucket: 'hybytes-rpm-repo'" >> /tmp/quickbackup/config.yml
      env:
        CONFIG_PATH: /tmp/quickbackup/config.yml

    # Step 5: Run Unit Tests
    - name: Run unit tests
      run: pytest tests/test_unit.py --tb=short
      env:
        CONFIG_PATH: /tmp/quickbackup/config.yml
        PYTHONPATH: ./src  # Add the src directory to PYTHONPATH

    # Step 6: Run Integration Tests
    - name: Run integration tests
      run: pytest tests/test_integration.py --tb=short
      env:
        CONFIG_PATH: /tmp/quickbackup/config.yml
        PYTHONPATH: ./src

    # Step 7: Run System Tests
    - name: Run system tests
      run: pytest tests/test_system.py --tb=short
      env:
        CONFIG_PATH: /tmp/quickbackup/config.yml
        PYTHONPATH: ./src

    # Step 8: Run Performance Tests
    - name: Run performance tests
      run: pytest tests/test_performance.py --tb=short
      env:
        CONFIG_PATH: /tmp/quickbackup/config.yml
        PYTHONPATH: ./src

    # Step 9: Run Security Tests (e.g. Bandit)
    - name: Run security validation tests
      run: |
        bandit -r ./src -o bandit_report.txt
        cat bandit_report.txt  # Show the report in the output
      env:
        CONFIG_PATH: /tmp/quickbackup/config.yml

    # Step 10: Run Dependency Scanning (e.g. Safety, Pip-audit)
    - name: Run dependency vulnerability scan (Safety & Pip-audit)
      run: |
        safety check --full-report > safety_report.txt
        pip-audit --output pip_audit_report.txt
        cat safety_report.txt
        cat pip_audit_report.txt
      env:
        CONFIG_PATH: /tmp/quickbackup/config.yml

