name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Step 4: Prepare test environment
    - name: Prepare test environment
      run: |
        mkdir -p /tmp/testdir
        echo "test content" > /tmp/testdir/testfile.txt
        mkdir -p /tmp/quickbackup
        echo "backup_paths: ['/tmp/testdir']" > /tmp/quickbackup/config.yml
        echo "s3_bucket: 'hybytes-rpm-repo'" >> /tmp/quickbackup/config.yml
      env:
        CONFIG_PATH: /tmp/quickbackup/config.yml

    # Step 5: Run Unit Tests
    - name: Run unit tests
      run: pytest tests/test_unit.py --tb=short
      env:
        CONFIG_PATH: /tmp/quickbackup/config.yml
        PYTHONPATH: ./src  # Add the src directory to PYTHONPATH






